"""initial migration

Revision ID: 4d08029053fa
Revises: 
Create Date: 2024-10-26 21:37:37.023892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d08029053fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Code', sa.String(length=500), nullable=True),
    sa.Column('Title', sa.String(length=500), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_Code'), ['Code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_Code'))

    op.drop_table('assessment')
    # ### end Alembic commands ###
