"""ADDING NEW COLUMN

Revision ID: e0b5e019709e
Revises: f15310cf05b1
Create Date: 2024-10-28 02:55:45.312985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b5e019709e'
down_revision = 'f15310cf05b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_column('Complete')

    # ### end Alembic commands ###
